base_last_name: list = [
    'andradino',
    'alves',
    'assunção',
    'adade',
    'andrade',
    'de andrade',
    'arteaga',
    'de amoedo',
    'bezerra',
    'berenicio',
    'barbosa',
    'baratela',
    'barros',
    'batista',
    'bonner',
    'bolsonaro',
    'brandão',
    'bragança',
    'borges',
    'campos',
    'conrado',
    'caetano',
    'do carmo',
    'castro',
    'cardoso',
    'carvalho',
    'carneiro',
    'cordeiro',
    'cornélio',
    'da costa',
    'dutra',
    'dias',
    'damaceno',
    'duarte',
    'ducarmo',
    'elídio',
    'ferreira',
    'fernandes',
    'filho',
    'fogaça',
    'frança',
    'freitas',
    'garcia',
    'garçon',
    'galileu',
    'gomes',
    'gom',
    'gonçalves',
    'gonzaga',
    'gusmão',
    'heliman',
    'ipiranga',
    'inácio',
    'de jesus',
    'kwartsu',
    'lacerda',
    'lamarques',
    'lopes',
    'lima',
    'leite',
    'leitão',
    'louro',
    'de lourdes',
    'machado',
    'marques',
    'mendonça',
    'macedo',
    'mendes',
    'miranda',
    'marcelino',
    'martins',
    'melo',
    'messias',
    'medeiros',
    'mosquini',
    'monteiro',
    'moraes',
    'moreira',
    'moura',
    'muniz',
    'munhoz',
    'neto',
    'de nobrega',
    'nascimento',
    'do nascimento',
    'nunes',
    'oliveira',
    'de oliveira',
    'pascoal',
    'padrão',
    'prado',
    'pinto',
    'pimenta',
    'pimentel',
    'pernambuco',
    'píres',
    'pereira',
    'de paula',
    'pedroso',
    'da ressurreição',
    'quintão',
    'ramos',
    'rangel',
    'rego',
    'reis',
    'rigoni',
    'ribeiro',
    'rodrigues',
    'santos',
    'dos santos',
    'santana',
    'do rosario',
    'de souza',
    'rocha',
    'da rocha',
    'silva',
    'da silva',
    'soares',
    'sobral',
    'sabatino',
    'teixeira',
    'tulíbio',
    'do universo',
    'vaz',
    'vieira',
    'washinton',
    'xavier',
    'xagas',
    'de yangladino',
    'zebedeu',
    'zibião',
]

if __name__ == '__main__':
    # Testar se tem nomes tepetidos
    import verificar_duplicidades as vd
    print(vd.valores_duplicados(base_last_name))